server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://servicediscovery:8070/eureka/

spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
          - Path=/inventory/**
          filters:
          - RewritePath=/inventory/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
        - id: loyalty-program-service
          uri: lb://loyalty-program-service
          predicates:
          - Path=/loyalty-program/**
          filters:
          - RewritePath=/loyalty-program/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
        - id: point-of-sale-service
          uri: lb://point-of-sale-service
          predicates:
          - Path=/point-of-sale/**
          filters:
          - RewritePath=/point-of-sale/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
        - id: keycloak-registration
          uri: lb://auth-service/register
          predicates:
            - Path=/auth-service/register
          filters:
            - name: RedirectTo
              args:
                status: "302"
                url: "http://localhost:8080/admin/realms/master/users"
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: keycloak-login
          uri: lb://auth-service/login
          predicates:
            - Path=/auth-service/login
          filters:
            - name: RedirectTo
              args:
                status: "302"
                url: "http://localhost:8080/realms/master/protocol/openid-connect/token"
            - RemoveRequestHeader= Cookie,Set-Cookie
        discovery.locator:
          enabled: true
          lowerCaseServiceId: true
   
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
        
        
        